[theme]
primaryColor = "#660066"             # Your purple brand colour
backgroundColor = "#FFFFFF"          # Main background (white)
secondaryBackgroundColor = "#F7F7F7" # Sidebars, widgets (light grey)
textColor = "#000000"                # Text colour (black)
font = "sans serif"
